eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/
    healthcheck:
      enabled: true
  hostname: localhost
  server:
    hostname: localhost
    port: 8761
  instance:
    instanceId: ${spring.application.instance_id:${random.value}}
    statusPageUrl: http://${eureka.hostname}:${server.port}/actuator/info
    healthCheckUrl: http://${eureka.hostname}:${server.port}/actuator/health
    homePageUrl: http://${eureka.hostname}/:${server.port}/actuator/info

spring:
  cloud:
    client:
      hostname: ${eureka.hostname}